# Generated by Django 3.1.6 on 2021-02-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_categories_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='age',
        ),
    ]
