# Generated by Django 3.1.6 on 2021-02-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_remove_categories_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='new.categories'),
        ),
    ]
